// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homepage-current/Current.tsx": () => import("../components/mockups/homepage-current/Current.tsx"),
  "./components/mockups/owlnest-brand-home/OwlnestBrandRitual.tsx": () => import("../components/mockups/owlnest-brand-home/OwlnestBrandRitual.tsx")
};
